### ISSUE TITLE
When the DS has a blank list of opmodes

### ISSUE THREAD

**Issue by lcdnbl** [gwarby/Team13460for2023#18]
@gwarby 
I just experienced the Driver Station presenting a blank list of op modes.  _This one time_ it was fixed entirely with the DS by:

1. Use the Android apps tab to shutdown the FTC Driver Station app
2. Use the pull down from the top of the Android screen to turn off DS wifi
3. Turn back on DS wifi
4. Re-open the FTC Driver Station app

Maybe we can add a Debug section to the README in order to close this issue.  (Or maybe the drive team can simply read it and delete it.)

**Comment by gwarby** [comment]
Good to know, I'll add it to the README, and keep it in mind for competition when I'm on the field. If it happens again (not in competition), we'll try to find the source.
