### ISSUE TITLE
Code needs field testing

### ISSUE THREAD

**Issue by lcdnbl** [gwarby/Team13460for2023#19]
@gwarby the code in branch "working_code_Dec09_2023":
- Is loaded on the robot
- Updated to use new 'arm limiter' servo / beam:
  - BlueBackPixel (also has untested updates for pixel loading on init)
  - BlueFrontPixel
  - RedBackPixel
  - RedFrontPixel
- Not updated to use the new 'arm limiter':
  - BlueFront  (doesn't try to place 2nd pixel)
  - RedFront (doesn't try to place 2nd pixel)

**Comment by chrisgeerts** [comment]
Problems found on 12/15/23. None resolved.
- blueBackPixel right side, too far to middle when placing pixel
- blueBackPixel left side doesn't back up far enough to board
- blueFrontPixel shows huge error
- redFrontPixel middle; pixel landed oddly
- redFrontPixel right; not far enough towards center

Additionally, tele-op is going to need work before matches 12/16/23.
