### ISSUE TITLE
Add drone launching controls with these servo positions

### ISSUE THREAD

**Issue by lcdnbl** [gwarby/Team13460for2023#4]
For the servo "dronelauncher", these positions were used for test firing drones at Tuesday's meeting:

- fire position: 0.15
- loaded position: 0.61

Code from Tuesday not directly committed, as it appears the gamepad controls being used for the dronelauncher potentially conflict with github code for 'ArmToGround / GrabTopPixel / ArmToHolding' that has not yet made it onto the robot.

**Comment by gwarby** [comment]
Added as dpad up
