### ISSUE TITLE
Flipper functions use grabber position to calculate wait times

### ISSUE THREAD

**Issue by lcdnbl** [gwarby/Team13460for2023#5]
@gwarby sorry for flagging this as an issue BOTH in PR#2 & here.  But I'm suggesting we close PR#2 without additional changes, because I thought the merged history would ultimately be cleaner if I merged the branches that PR#1 & PR#2 are reviewing before piling on the Tuesday meeting changes.

Like the title says, the 3 flipper command functions at the end of BlueBackPixel.java are calculating the travel distance, and then the wait time based on the position of the grabber (instead of the flipper).

**Comment by gwarby** [comment]
@lcdnbl I don't see the error, either it's fixed or I'm looking in the wrong place, but I don't see the problem. I'm looking in the finishing autonomous branch, for both red and blue pixel

**Comment by gwarby** [comment]
The pull request from auto the main hasn't been completed, so if that's where you're looking, I don't see the problem. Please elaborate.

**Comment by lcdnbl** [comment]
This line is good:
`private void reverseFlipper() { flipper.setPosition(CLAW_FLIP_SERVO_FLIPPED_POS); }`

But this is the 'Wait' version of the same flipper function, and the math & setting is using the grabber (2nd and 3rd lines below):
```
  private void reverseFlipperWait() {
    double distance = Math.abs(grabber.getPosition() - CLAW_FLIP_SERVO_FLIPPED_POS);
    grabber.setPosition(CLAW_FLIP_SERVO_FLIPPED_POS);
    sleep((int) (distance * CALC_FLIPPER_WAIT_MS + 5));
```

**Comment by gwarby** [comment]
Thanks for the clarification, it's fixed in main.

**Comment by gwarby** [comment]
Thanks for the clarification. It's been resolved in red and blue pixel.
